apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rtyb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rtyb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rtyb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rtyb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rtyb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xjrf-tenant/rhtap-demo-app/hacbs-test-project-rtyb@sha256:9af878393c2bdf5a76e1066f40c5c045b1a63dee72a355c301c377fd817b5576
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
