apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rtyb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xjrf-tenant/rhtap-demo-app/hacbs-test-project-rtyb@sha256:2eedecfea495f376c9c7f72d2822cc138b70b07961505ca00f623ee151843fe5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
